/**
 * @Author;Training
 * redux中的action文件中的type类型定义
 * 此文件的意义是将所有的type集合于一处,以便调用,方便管理
 */
export default {
    THEME_CHANGE:'THEME_CHANGE',
    POPULAR_REFRESH:'POPULAR_REFRESH',
    POPULAR_FAIL:"POPULAR_FAIL",
    POPULAR_SUCCESS:"POPULAR_SUCCESS",
    POPULAR_LOAD_MORE_SUCCESS:"POPULAR_LOAD_MORE_SUCCESS",
    POPULAR_LOAD_MORE_FAIL:"POPULAR_LOAD_MORE_FAIL",

    FAVORITE_SUCCESS:"FAVORITE_SUCCESS",
    FAVORITE_FAIL:"FAVORITE_FAIL",
    FAVORITE_GET_SUCCESS:"FAVORITE_GET_SUCCESS",
    FAVORITE_GET_FAIL:"FAVORITE_GET_FAIL",
    FAVORITE_GET_RELOAD:"FAVORITE_GET_RELOAD",

    TRENDING_REFRESH:'TRENDING_REFRESH',
    TRENDING_FAIL:"TRENDING_FAIL",
    TRENDING_SUCCESS:"TRENDING_SUCCESS",
    TRENDING_LOAD_MORE_SUCCESS:"TRENDING_LOAD_MORE_SUCCESS",
    TRENDING_LOAD_MORE_FAIL:"TRENDING_LOAD_MORE_FAIL",

}